"""update

Revision ID: 02d585e41ce4
Revises: 15643a9a9382
Create Date: 2024-05-06 10:32:56.592837

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '02d585e41ce4'
down_revision = '15643a9a9382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
