"""update

Revision ID: 17cc496d3f66
Revises: 6362964c3cf5
Create Date: 2024-05-14 17:25:45.443692

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '17cc496d3f66'
down_revision = '6362964c3cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
