"""update

Revision ID: 1bcf787bbaac
Revises: 5c9b813705ff
Create Date: 2024-05-04 10:43:51.217316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1bcf787bbaac'
down_revision = '5c9b813705ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
