"""Add age column to student

Revision ID: 209f490b2d36
Revises: 17cc496d3f66
Create Date: 2024-05-29 12:49:00.518485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '209f490b2d36'
down_revision = '17cc496d3f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcement', 'content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('announcement', 'announcement_time',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('comment', 'content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('course', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('course', 'textbook',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('course', 'class_time',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('course', 'class_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('course', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('student', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('gpa', sa.Float(), nullable=True))
    op.add_column('student', sa.Column('advisor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('home_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'home_address')
    op.drop_column('student', 'contact_number')
    op.drop_column('student', 'advisor')
    op.drop_column('student', 'gpa')
    op.drop_column('student', 'grade')
    op.drop_column('student', 'age')
    op.alter_column('course', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('course', 'class_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('course', 'class_time',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('course', 'textbook',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('course', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('comment', 'content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('announcement', 'announcement_time',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('announcement', 'content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
