"""update

Revision ID: 29500158e0aa
Revises: ac737ce6b0b2
Create Date: 2024-05-05 17:35:53.026018

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29500158e0aa'
down_revision = 'ac737ce6b0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'max_capacity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('course', 'current_capacity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'current_capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('course', 'max_capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
