"""update

Revision ID: 58b4e9d0d1e5
Revises: c86ae941c3c1
Create Date: 2024-05-05 14:43:59.226047

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '58b4e9d0d1e5'
down_revision = 'c86ae941c3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_ibfk_1', 'course', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('course_ibfk_1', 'course', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
