"""update

Revision ID: 5b4e6339754e
Revises: 02d585e41ce4
Create Date: 2024-05-06 15:27:25.843350

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b4e6339754e'
down_revision = '02d585e41ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('student', 'classLocation',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'classLocation',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('student', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
