"""update

Revision ID: 6362964c3cf5
Revises: 5b4e6339754e
Create Date: 2024-05-10 17:33:48.585906

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6362964c3cf5'
down_revision = '5b4e6339754e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
