"""update

Revision ID: 664f830fc0c5
Revises: 6e3a1b55848e
Create Date: 2024-06-03 17:23:12.951626

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '664f830fc0c5'
down_revision = '6e3a1b55848e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('img', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('teacher', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('teacher', sa.Column('homepage', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('teacher', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('teacher', sa.Column('postalCode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('teacher', sa.Column('Education', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'Education')
    op.drop_column('teacher', 'postalCode')
    op.drop_column('teacher', 'address')
    op.drop_column('teacher', 'homepage')
    op.drop_column('teacher', 'phone')
    op.drop_column('teacher', 'img')
    # ### end Alembic commands ###
