"""update

Revision ID: 6995af1ccc5a
Revises: 58b4e9d0d1e5
Create Date: 2024-05-05 14:51:04.134149

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6995af1ccc5a'
down_revision = '58b4e9d0d1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course', 'teacher', ['teacher_id'], ['id'])
    op.drop_column('student', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'course', type_='foreignkey')
    # ### end Alembic commands ###
