"""add img address

Revision ID: 76c5489dd4f9
Revises: f0ef1a2180e4
Create Date: 2024-05-30 11:46:05.065521

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '76c5489dd4f9'
down_revision = 'f0ef1a2180e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'avatar')
    # ### end Alembic commands ###
