"""update

Revision ID: 9ccbc29d4e0f
Revises: b33884197731
Create Date: 2024-05-05 14:30:18.540292

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ccbc29d4e0f'
down_revision = 'b33884197731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'teacher_id')
    # ### end Alembic commands ###
