"""update

Revision ID: ac737ce6b0b2
Revises: 70647fac3f53
Create Date: 2024-05-05 15:36:26.342718

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac737ce6b0b2'
down_revision = '70647fac3f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollmentlist',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'student_id')
    )
    op.drop_table('studentcourselink')
    op.add_column('course', sa.Column('max_capacity', sa.Integer(), nullable=False))
    op.add_column('course', sa.Column('current_capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'current_capacity')
    op.drop_column('course', 'max_capacity')
    op.create_table('studentcourselink',
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='studentcourselink_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='studentcourselink_ibfk_2'),
    sa.PrimaryKeyConstraint('course_id', 'student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('enrollmentlist')
    # ### end Alembic commands ###
