"""update

Revision ID: b33884197731
Revises: f230b2016474
Create Date: 2024-05-05 14:12:33.059198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b33884197731'
down_revision = 'f230b2016474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'book')
    op.drop_column('course', 'time')
    op.drop_column('course', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('course', sa.Column('time', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('course', sa.Column('book', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
