"""update

Revision ID: c86ae941c3c1
Revises: 9ccbc29d4e0f
Create Date: 2024-05-05 14:35:51.190493

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c86ae941c3c1'
down_revision = '9ccbc29d4e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
