"""update

Revision ID: e0b127e18040
Revises: 6a9a00ac26a9
Create Date: 2024-05-05 14:53:46.853107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e0b127e18040'
down_revision = '6a9a00ac26a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
