"""update

Revision ID: ed8dfc30bee5
Revises: aba0365ee16e
Create Date: 2024-05-04 17:21:06.324809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ed8dfc30bee5'
down_revision = 'aba0365ee16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('user_type', sa.Enum('admin', 'student', 'teacher', name='usertype'), nullable=False))
    op.create_foreign_key(None, 'user', 'student', ['student_id'], ['id'])
    op.create_foreign_key(None, 'user', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'teacher_id')
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###
