"""update

Revision ID: f230b2016474
Revises: f89ead0acdf6
Create Date: 2024-05-05 12:22:47.648807

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f230b2016474'
down_revision = 'f89ead0acdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('book', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'status')
    op.drop_column('course', 'time')
    op.drop_column('course', 'book')
    # ### end Alembic commands ###
