"""update

Revision ID: f89ead0acdf6
Revises: f904aba27e17
Create Date: 2024-05-04 22:47:35.971397

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f89ead0acdf6'
down_revision = 'f904aba27e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'name')
    op.drop_column('teacher', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('teacher', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
