"""update

Revision ID: f904aba27e17
Revises: ed8dfc30bee5
Create Date: 2024-05-04 18:20:42.514531

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f904aba27e17'
down_revision = 'ed8dfc30bee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
